codegeneration/CodeGenerator.js
index.js
test/helpers.js
test/type-constructors.test.js

Export language-specific functions so that package users don't have to construct their own generators. Will be much nicer to demo.

Add toPython and toJava

---

codegeneration/CSharpGenerator.js
index.js
test/built-in-types.json
test/helpers.js
test/type-constructors.test.js

This just sets up a c-sharp generator to work with the module and hooks up the tests / unsupported types to `test/helpers.js` and `type-constructors.test.js`.
With this PR, the following tests are working:
As I was working on this, I had a question about Octals. It seems that ecmascript doesn't allow for [octals anymore](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt) (scroll down a bit, can't get a link to that section). C# also doesn't have octals. If someone does end up typing `01234567` as an octal, is that technically just `1234567` in integer format? I am just `parseInt()`ing that at the moment, but probably need to change it maybe?

COMPASS-2624: simple C# generator

---

codegeneration/CSharpGenerator.js
test/built-in-types.json
test/helpers.js

C# does the same thing as python -- needs date numbers as separate arguments. 
The only quirk is that the `now` constructor doesn't need the `new` word. not quite sure why, but tried it out in [C# playground](https://dotnetfiddle.net/) and it works as just `DateTime.Now`.

make dates work in csharp

---

codegeneration/SymbolTable.js
index.js

Previously, for no good reason, we were generating the symbol table once but assigning it to the generator for each `compileECMAScript` call. Now the generator gets assigned it's symbols when it's first instantiated and not again, since it won't change. 
`generateSymbolTable` now returns an object instead of an array, so that we can use `Object.assign` instead of copying it by hand.

Add symbol to generator once

---

codegeneration/CodeGenerator.js
codegeneration/JavaGenerator.js

This is in preparation for accepting multiple input languages. None of the target-language-specific generators (i.e. JavaGenerator.js, Python3Generator.js, etc) should have any of their own `visitX` methods since that is input-language PST specific. Everything input-language specific should go in CodeGenerator.py.

Remove all visit methods from JavaGenerator

---

README.md
codegeneration/java/Generator.js
codegeneration/javascript/Visitor.js
codegeneration/shell/Visitor.js
index.js
package.json
symbols/javascript/symbols.yaml
symbols/shell/types.yaml
test/code-generation.test.js
test/helpers.js
test/json/success/bson-constructors.json
test/json/success/bson-object-methods.json
test/json/success/bson-utils.json
test/json/success/js-constructors.json
test/json/success/js-utils.json

Now usage should look like:
```
const input = 'javascript';
const output = 'java';
const compiler = require('bson-compilers');
compiler[input][output]("some code in js to compile to java");
// or
compiler.javascript.java("some code in js to compile to java");
```
Tests have been updated to use the new API. Also some minor style/comment fixes.

Update package API and tests

---

test/code-generation.test.js
test/helpers.js
test/json/error/javascript/bson-constructors.json
test/json/error/shell/bson-constructors.json
test/json/success/javascript/bson-constructors.json
test/json/success/javascript/bson-object-methods.json
test/json/success/javascript/bson-utils.json
test/json/success/javascript/js-constructors.json
test/json/success/javascript/js-utils.json
test/json/success/shell/bson-constructors.json
test/json/success/shell/bson-object-methods.json
test/json/success/shell/bson-utils.json
test/json/success/shell/js-constructors.json
test/json/success/shell/js-utils.json

Previously our test suite expected all translations to be symmetric, but that's not always possible (especially as our generated code gets more idiomatic). 
For example, Code in javascript can accept a function or a string, but in shell it only accepts a string.
Javascript --> Shell:
```
Code(function(x){console.log(x)};) --> Code("function(x){console.log(x)};")
```
Shell --> Javascript 
```
Code("function(x){console.log(x)};") --> Code("function(x){console.log(x)};")
```
So now we have a folder for each output language, and in that folder the JSON files will only be tested from input language --> target language.

COMPASS-2754 - Separate json test files by input language

---

codegeneration/java/Generator.js
codegeneration/javascript/Visitor.js
package.json
test/json/success/javascript/bson-constructors.json
test/json/success/javascript/bson-object-methods.json

- Include BSON numeric types when type checking for "numeric" arguments.
- Indicate if an argument, that is of the wrong type, is also optional in the error message.
- In preparation for updating the numeric types to match the language defaults,  switch all the tests from using numbers to strings where possible. Doing this to save a lot of typing when `1` in javascript starts generating `java.lang.Long("1")`.
- Fix a bug where we were generating a int that is too large for java to handle.

Misc bug fixes

---

codegeneration/shell/Visitor.js

Because `minKey`, `new MinKey`, `MinKey()` and `new MinKey()` are all valid and equivalent, we need to special case the `visitIdentifierExpression` in the shell visitor. What this is doing is basically rearranging the tree so the identifier on it's own becomes a function call. 
If the visitor encounters a `MinKey` identifier that is not part of a `newExpression` or a `FuncCallExpression`, then it will create a fake "FunctionCallExpressionContext" (`node`) and calls `visitFuncCallExpressionExpression` on it directly so from the generators perspective, it's exactly the same as if the original code was `MinKey()`. 
Also true for MaxKey.

Turn Max/MinKey into function call for shell

---

codegeneration/javascript/Visitor.js
test/json/success/javascript/bson-constructors.json

Remove support for weird syntax like `new MaxKey` or `new ObjectId` because nobody seems to have heard of it and it's a headache to maintain. Merging bc we talked about it at standup.

Remove support for new X

---

codegeneration/python/Generator.js

I noticed that it's not happening in a few places, which was causing bugs in attribute access.

Set ctx.type in emit methods

---

package.json
test/code-generation.test.js
test/helpers.js

allows for us to run tests individually for each input/output language.
The way to use this is:
```shell
$ OUTPUT=python,java INPUT=javascript npm run test
```
If none are provided, will default to everything we have. Probably for most cases we'd only be ever doing one input and one output, or everything all together so I think this is a nice quick approach to speed up testing.

accept env variables as output/input params

---

README.md
index.js

Each language exports a string including the required imports now. Can be used in the UI to indicate which packages are being used.
Currently, doesn't do anything "smart", and just lists all the packages that can be used. In the future we could add detection for classes that are getting used and only show imports for those classes, but for now we import everything.
TODO: make sure we're importing in the most 'idiomatic' way.

Add import string as export

---

test/code-generation.test.js
test/helpers.js

Can set MODE env var to "success" or "error" so that we don't have to run the whole test suite if we're just testing errors.
Also adds an optional error message field if we want to test the error message contains some string. I want this because I'm writing "unimplemented" errors and I want to make sure that the error messages are getting generated correctly.

Allow running test by mode

---

index.js

import strings all have a starting new line break which shouldn't be there for the UI portion of things. Removing it for now so I don't have to strip it in the UI.

remove initial \n in import strings

---

index.js

confuses people a bit! so removing this package naming for now!

remove example package name in java imports

---

codegeneration/java/Generator.js
codegeneration/javascript/Visitor.js
index.js
test/idiomatic-error.test.js
test/idiomatic.test.js

Adds support for generating java code using the [builders classes](http://mongodb.github.io/mongo-java-driver/3.6/builders/).
The API has changed in that it now takes an optional second argument, "idiomatic", which if true will generate java using the builders. TODO: do we want to automatically generate with builders, or documents?
The other set of changes are within the Java Generator, now each operator has a method that will generate the correct builder. I added a lot of comments so hopefully the code is clear.
When this is merged, we'll be done with "idiomatic" java!
Please take a look!

Support for using Java generators.

---

codegeneration/javascript/Visitor.js
codegeneration/shell/Visitor.js
index.js
test/idiomatic.test.js
test/json/success/javascript/bson-constructors.json
test/json/success/shell/bson-constructors.json
test/non-idiomatic.test.js

Previously, if there was no second argument to `compile` it would default to not using idiomatic java. This PR:
- Switches the default to true if no argument is passed in
- Updates the test suite so that the expected values are idiomatic
- Moves the old document tests for non-idiomatic java into test/non-idiomatic.test.js
- Updates the `Code` constructors for javascript and shell so that they always generate non-idiomatic code for the scope argument. So instead of generating `new CodeWithScope("x", eq("x", 1L))`, it will generate `new CodeWithScope("x", new Document("x", 1L))` no matter if idiomatic is turned on or not.

Set default compile to use builders

---

codegeneration/csharp/Generator.js
codegeneration/java/Generator.js
codegeneration/javascript/Generator.js
codegeneration/javascript/Visitor.js
codegeneration/python/Generator.js
codegeneration/shell/Generator.js

This is the last major thing that needed to be done before we can start on adding new visitors/input languages.
This PR adds accessor methods to the visitor so that the generator does not need to call or know anything specific about the tree being traversed. 
For example: previously to get the arguments of a function call, the generator would call `ctx.arguments().argumentsList().singleExpression()`. Now it just calls `this.getArguments(ctx)`, which is defined in the visitor (which returns `ctx.arguments().argumentsList().singleExpression()`).
This is required because when we have multiple trees, the tree access will have different names (or even different shapes) so we want to abstract the data access to the visitor so the generators can be truly input-language agnostic.
As I was going …

Generators never directly access the tree

---

package.json

This PR adds the git URL to package.json so compass can exclude it as a third party dependency when generating licensing information.

COMPASS-3823: Add git info for license metadata

---

.github/workflows/run-tests.yml
.travis.yml
codegeneration/CodeGenerationVisitor.js
codegeneration/javascript/Generator.js
codegeneration/javascript/Visitor.js
package.json
test/functions.test.js

- Allow functions to be compiled to javascript.
- Throws `Support for exporting functions to languages other than javascript is not yet available.` for other languages.
Other changes:
- Move CI from travis to github workflows
NOTE: Arrow functions are not supported by the grammar. Updating the grammar with a [newer version](https://raw.githubusercontent.com/antlr/grammars-v4/master/javascript/ecmascript/JavaScript/ECMAScript.g4) breaks other features.

feat: compile functions to js
